import { io } from "socket.io-client";
import { useDispatch } from "react-redux";
import styles from "../styles/Home.module.css";
import About from "../components/About";
import BotInfo from "../components/BotInfo";
import CoinInfo from "../components/CoinInfo";
import FooterInfo from "../components/FooterInfo";
import Karabil from "../components/Karabil";
import WhyUse from "../components/WhyUse";
import content from "../content";
//Next js imports
import Head from "next/head";

// useEffect(() => {
//   const socket = io("http://localhost:3000");
//   socket.on("connect", () => {
//     console.log("YAY you connected");
//   });
//   socket.on("receive-coinData", (coinData) => {
//     console.log(coinData);
//     setCoinDataState(coinData);
//   });
// }, []);
export async function getServerSideProps() {
  try {
    const responseBTC = await fetch("http://localhost:5000/getBTCData");
    const { BTCPrice } = await responseBTC.json();
    const responseADA = await fetch("http://localhost:5000/getADAData");
    const { ADAPrice } = await responseADA.json();
    const responseETH = await fetch("http://localhost:5000/getETHData");
    const { ETHPrice } = await responseETH.json();
    const responseUSDT = await fetch("http://localhost:5000/getUSDTData");
    const { USDTPrice } = await responseUSDT.json();
    const responseCoinData = await fetch("http://localhost:5000/getCoinData");
    const coinData = await responseCoinData.json();
    return {
      props: {
        BTCPrice,
        ADAPrice,
        ETHPrice,
        USDTPrice,
        coinData,
      },
    };
  } catch (error) {
    throw new Error(error);
  }
}

export default function Home({
  BTCPrice,
  ADAPrice,
  ETHPrice,
  USDTPrice,
  coinData,
}) {
  const dispatch = useDispatch();
  dispatch({ type: content.types.GET_BTC_PRICE, payload: BTCPrice });
  dispatch({ type: content.types.GET_ADA_PRICE, payload: ADAPrice });
  dispatch({ type: content.types.GET_ETH_PRICE, payload: ETHPrice });
  dispatch({ type: content.types.GET_USDT_PRICE, payload: USDTPrice });
  dispatch({
    type: content.types.GET_COIN_BTC_DATA,
    payload: coinData.data.btcData,
  });
  dispatch({
    type: content.types.GET_COIN_ADA_DATA,
    payload: coinData.data.adaData,
  });
  dispatch({
    type: content.types.GET_COIN_ETH_DATA,
    payload: coinData.data.ethData,
  });
  dispatch({
    type: content.types.GET_COIN_USDT_DATA,
    payload: coinData.data.usdtData,
  });
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>| Mereo |</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <Karabil />
          <About />
          <WhyUse />
          <CoinInfo />
          <BotInfo />
          <FooterInfo />
        </div>
      </div>
    </>
  );
}
