// import { io } from "socket.io-client";
import { useEffect, useState } from "react";
import GlobalStyle from "../GlobalStyles";
// import {
// BrowserRouter as Router,
// Routes,
// Route,
// BrowserRouter,
// } from "react-router-dom";
//Global styles
// import GlobalStyle from "./GlobalStyles";
//
//Pages
// import Home from "./pages/Home";
// import Contact from "./pages/Contact";
// import AboutUs from "./pages/AboutUs";
// import NotFound from "./pages/NotFound";
// import Bots from "./pages/Bots";
// import Coins from "./pages/Coins";
//Components
// import Header from "./components/Header";
// import Footer from "./components/Footer";
import styles from "../styles/Home.module.css";
import About from "../components/About";
import BotInfo from "../components/BotInfo";
import CoinInfo from "../components/CoinInfo";
import FooterInfo from "../components/FooterInfo";
import Karabil from "../components/Karabil";
import WhyUse from "../components/WhyUse";
//Next js imports
import Head from "next/head";
import Image from "next/image";
// const [coinDataState, setCoinDataState] = useState(0);

// useEffect(() => {
//   const socket = io("http://localhost:3000");
//   socket.on("connect", () => {
//     console.log("YAY you connected");
//   });
//   socket.on("receive-coinData", (coinData) => {
//     console.log(coinData);
//     setCoinDataState(coinData);
//   });
// }, []);

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <Karabil />
          <About />
          <WhyUse />
          <CoinInfo />
          <BotInfo />
          <FooterInfo />
        </div>
      </div>
      <GlobalStyle />
    </>
  );
}
